sudo: false

# Define the language and versions that mdl is written in
language: python
python:
  - 3.5

# Run tests only against the master branch
branches:
  only:
    - master

# Setup global environmental variables
env:
    - PYTHONPATH=./ MDL_CONFIGDIR=$HOME/.mdl_unittests/config
#  global:
#    - PYTHONPATH=./ MDL_CONFIGDIR=$HOME/.mdl_unittests/config

# Install PIP packages and create a temporary config file before installing
before_install:
    - pip install -r requirements.txt
    - mdl/test/create_test_config.py
    - mysql -e 'CREATE DATABASE test_mdl;'

# Install mdl
install: python3 setup.py

# Run the unittest scripts
script: mdl/test/_do_all_tests.py

# Define the services we'll need running
services:
  - mysql

addons:
  mariadb: '10.0'
