main:
    log_directory:
    log_level: debug
    listen_address: 0.0.0.0
    bind_port: 3000
    memcached_hostname: localhost
    memcached_port: 11211
    sqlalchemy_pool_size: 10
    sqlalchemy_max_overflow: 10
    infoset_server_name: localhost
    infoset_server_port: 6000
    infoset_server_https: False
    infoset_server_uri: /infoset/api/v1
    interval:60
    db_hostname: localhost
    db_username: mdl
    db_password: PASSWORD
    db_name: mdl
